# Generated by Django 5.2.7 on 2025-12-24 17:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='faq',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_faqs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='faq',
            name='related_faqs',
            field=models.ManyToManyField(blank=True, to='core.faq'),
        ),
        migrations.AddField(
            model_name='faq',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_faqs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='impactmetric',
            name='last_updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='newslettersubscription',
            index=models.Index(fields=['email', 'is_active'], name='core_newsle_email_1dc2b3_idx'),
        ),
        migrations.AddIndex(
            model_name='newslettersubscription',
            index=models.Index(fields=['is_active', 'is_verified'], name='core_newsle_is_acti_878380_idx'),
        ),
        migrations.AddField(
            model_name='sitepage',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_pages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sitepage',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='core.sitepage'),
        ),
        migrations.AddField(
            model_name='sitepage',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_pages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='teammember',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='team_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='faq',
            index=models.Index(fields=['category', 'is_published'], name='core_faq_categor_378ca3_idx'),
        ),
        migrations.AddIndex(
            model_name='faq',
            index=models.Index(fields=['is_featured', 'is_published'], name='core_faq_is_feat_e708ec_idx'),
        ),
        migrations.AddIndex(
            model_name='impactmetric',
            index=models.Index(fields=['metric_type', 'is_public'], name='core_impact_metric__57c2ee_idx'),
        ),
        migrations.AddIndex(
            model_name='sitepage',
            index=models.Index(fields=['slug', 'is_published'], name='core_sitepa_slug_cf4207_idx'),
        ),
        migrations.AddIndex(
            model_name='sitepage',
            index=models.Index(fields=['show_in_navigation', 'is_published'], name='core_sitepa_show_in_03e57a_idx'),
        ),
    ]
