# Generated by Django 5.2.7 on 2025-12-24 17:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('partners', '0001_initial'),
        ('programs', '0001_initial'),
        ('research', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='partnercontact',
            name='added_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='partnerevaluation',
            name='evaluated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partner_evaluations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='partnerorganization',
            name='focal_point',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partner_focal_points', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='partnerorganization',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_partners', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='partnerevaluation',
            name='partner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='partners.partnerorganization'),
        ),
        migrations.AddField(
            model_name='partnercontact',
            name='partner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='partners.partnerorganization'),
        ),
        migrations.AddField(
            model_name='partnershipagreement',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_agreements', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='partnershipagreement',
            name='our_signatory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='signed_agreements_our', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='partnershipagreement',
            name='partner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agreements', to='partners.partnerorganization'),
        ),
        migrations.AddField(
            model_name='partnershipmeeting',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='partnershipmeeting',
            name='partner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meetings', to='partners.partnerorganization'),
        ),
        migrations.AddField(
            model_name='partnershipmeeting',
            name='yes_team',
            field=models.ManyToManyField(blank=True, related_name='partner_meetings_yes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='partnershipopportunity',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partnership_opportunities', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='partnershipopportunity',
            name='converted_partner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='converted_opportunities', to='partners.partnerorganization'),
        ),
        migrations.AddField(
            model_name='partnershipopportunity',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='partnershipopportunity',
            name='team_members',
            field=models.ManyToManyField(blank=True, related_name='opportunity_teams', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='partnershipproject',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='partnershipproject',
            name='partner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='partners.partnerorganization'),
        ),
        migrations.AddField(
            model_name='partnershipproject',
            name='program',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partnership_projects', to='programs.program'),
        ),
        migrations.AddField(
            model_name='partnershipproject',
            name='project_lead',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='led_partnership_projects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='partnershipproject',
            name='research_project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partnership_projects', to='research.researchproject'),
        ),
        migrations.AddField(
            model_name='partnershipproject',
            name='team_members',
            field=models.ManyToManyField(blank=True, related_name='partnership_project_teams', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='partnershipmeeting',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='meetings', to='partners.partnershipproject'),
        ),
        migrations.AddField(
            model_name='partnershipresource',
            name='partner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='partners.partnerorganization'),
        ),
        migrations.AddField(
            model_name='partnershipresource',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resources', to='partners.partnershipproject'),
        ),
        migrations.AddField(
            model_name='partnershipresource',
            name='uploaded_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='partnerorganization',
            index=models.Index(fields=['slug', 'status'], name='partners_pa_slug_cf109d_idx'),
        ),
        migrations.AddIndex(
            model_name='partnerorganization',
            index=models.Index(fields=['organization_type', 'partnership_level'], name='partners_pa_organiz_fce85a_idx'),
        ),
        migrations.AddIndex(
            model_name='partnerorganization',
            index=models.Index(fields=['country', 'city'], name='partners_pa_country_97279f_idx'),
        ),
        migrations.AddIndex(
            model_name='partnerorganization',
            index=models.Index(fields=['is_featured', 'is_public'], name='partners_pa_is_feat_3850e1_idx'),
        ),
    ]
