# Generated by Django 5.2.7 on 2025-12-24 17:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mentorship', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='mentorshipapplication',
            name='applicant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentorship_applications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mentorshipapplication',
            name='reviewer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_mentorship_applications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mentorshipfeedback',
            name='provided_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='given_feedback', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mentorshipfeedback',
            name='provided_for',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_feedback', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mentorshipgoal',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mentorshipmatch',
            name='matched_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_matches', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mentorshipmatch',
            name='mentee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentee_matches', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mentorshipmatch',
            name='mentor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentor_matches', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mentorshipgoal',
            name='match',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentorship_goals', to='mentorship.mentorshipmatch'),
        ),
        migrations.AddField(
            model_name='mentorshipfeedback',
            name='match',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mentorship.mentorshipmatch'),
        ),
        migrations.AddField(
            model_name='mentorshipprogram',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_mentorship_programs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mentorshipprogram',
            name='mentors',
            field=models.ManyToManyField(blank=True, related_name='mentor_programs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mentorshipprogram',
            name='program_coordinator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coordinated_mentorship_programs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mentorshipmatch',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='mentorship.mentorshipprogram'),
        ),
        migrations.AddField(
            model_name='mentorshipfeedback',
            name='program',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mentorship.mentorshipprogram'),
        ),
        migrations.AddField(
            model_name='mentorshipapplication',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='mentorship.mentorshipprogram'),
        ),
        migrations.AddField(
            model_name='mentorshipresource',
            name='match',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='match_resources', to='mentorship.mentorshipmatch'),
        ),
        migrations.AddField(
            model_name='mentorshipresource',
            name='program',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='program_resources', to='mentorship.mentorshipprogram'),
        ),
        migrations.AddField(
            model_name='mentorshipresource',
            name='uploaded_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mentorshipsession',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mentorshipsession',
            name='match',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='mentorship.mentorshipmatch'),
        ),
        migrations.AddField(
            model_name='mentorshipfeedback',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mentorship.mentorshipsession'),
        ),
        migrations.AddIndex(
            model_name='mentorshipprogram',
            index=models.Index(fields=['slug', 'status'], name='mentorship__slug_843349_idx'),
        ),
        migrations.AddIndex(
            model_name='mentorshipprogram',
            index=models.Index(fields=['program_type', 'status'], name='mentorship__program_355dcc_idx'),
        ),
        migrations.AddIndex(
            model_name='mentorshipprogram',
            index=models.Index(fields=['is_featured', 'is_published'], name='mentorship__is_feat_c1e9a7_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='mentorshipmatch',
            unique_together={('program', 'mentor', 'mentee')},
        ),
        migrations.AlterUniqueTogether(
            name='mentorshipapplication',
            unique_together={('program', 'applicant')},
        ),
    ]
