# Generated by Django 5.2.7 on 2025-12-24 17:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('blog', '0001_initial'),
        ('programs', '0001_initial'),
        ('research', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='blogcomment',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='blog_comments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='blogcomment',
            name='moderated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moderated_comments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='blogcomment',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='blog.blogcomment'),
        ),
        migrations.AddField(
            model_name='bloglike',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog_likes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog_posts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='posts', to='blog.blogcategory'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='co_authors',
            field=models.ManyToManyField(blank=True, related_name='coauthored_posts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='editor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='edited_posts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='last_modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='last_modified_posts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='related_posts',
            field=models.ManyToManyField(blank=True, to='blog.blogpost'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='related_programs',
            field=models.ManyToManyField(blank=True, related_name='blog_posts', to='programs.program'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='related_projects',
            field=models.ManyToManyField(blank=True, related_name='blog_posts', to='research.researchproject'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='related_publications',
            field=models.ManyToManyField(blank=True, related_name='blog_posts', to='research.researchpublication'),
        ),
        migrations.AddField(
            model_name='bloglike',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_likes', to='blog.blogpost'),
        ),
        migrations.AddField(
            model_name='blogcomment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='blog.blogpost'),
        ),
        migrations.AddField(
            model_name='blogseries',
            name='posts',
            field=models.ManyToManyField(blank=True, related_name='series', to='blog.blogpost'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='blog_posts', to='blog.blogtag'),
        ),
        migrations.AddField(
            model_name='blogview',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_views', to='blog.blogpost'),
        ),
        migrations.AddField(
            model_name='blogview',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='newsletterpost',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='newsletter_sends', to='blog.blogpost'),
        ),
        migrations.AlterUniqueTogether(
            name='bloglike',
            unique_together={('post', 'user')},
        ),
        migrations.AddIndex(
            model_name='blogcomment',
            index=models.Index(fields=['post', 'status'], name='blog_blogco_post_id_5f3ca3_idx'),
        ),
        migrations.AddIndex(
            model_name='blogcomment',
            index=models.Index(fields=['author', 'status'], name='blog_blogco_author__9fc2a3_idx'),
        ),
        migrations.AddIndex(
            model_name='blogpost',
            index=models.Index(fields=['slug', 'status'], name='blog_blogpo_slug_0e8f9e_idx'),
        ),
        migrations.AddIndex(
            model_name='blogpost',
            index=models.Index(fields=['category', 'status'], name='blog_blogpo_categor_2e8dab_idx'),
        ),
        migrations.AddIndex(
            model_name='blogpost',
            index=models.Index(fields=['is_featured', 'status'], name='blog_blogpo_is_feat_eb28c3_idx'),
        ),
        migrations.AddIndex(
            model_name='blogpost',
            index=models.Index(fields=['published_at', 'status'], name='blog_blogpo_publish_d6ae47_idx'),
        ),
        migrations.AddIndex(
            model_name='blogview',
            index=models.Index(fields=['post', 'created_at'], name='blog_blogvi_post_id_63bd78_idx'),
        ),
        migrations.AddIndex(
            model_name='blogview',
            index=models.Index(fields=['user', 'created_at'], name='blog_blogvi_user_id_93b87e_idx'),
        ),
    ]
