# Generated by Django 5.2.7 on 2025-12-24 17:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('partners', '0002_initial'),
        ('programs', '0002_initial'),
        ('research', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='literaturereview',
            name='conducted_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='researchdataset',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='researchproject',
            name='co_investigators',
            field=models.ManyToManyField(blank=True, related_name='co_investigated_projects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='researchproject',
            name='datasets',
            field=models.ManyToManyField(blank=True, related_name='projects', to='research.researchdataset'),
        ),
        migrations.AddField(
            model_name='researchproject',
            name='partners',
            field=models.ManyToManyField(blank=True, related_name='research_projects', to='partners.partnerorganization'),
        ),
        migrations.AddField(
            model_name='researchproject',
            name='principal_investigator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='led_projects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='researchproject',
            name='research_assistants',
            field=models.ManyToManyField(blank=True, related_name='assisted_projects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='researchpublication',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='publications', to='research.researchcategory'),
        ),
        migrations.AddField(
            model_name='researchpublication',
            name='contributors',
            field=models.ManyToManyField(blank=True, related_name='contributed_publications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='researchpublication',
            name='corresponding_author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='corresponding_publications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='researchpublication',
            name='related_programs',
            field=models.ManyToManyField(blank=True, related_name='research_publications', to='programs.program'),
        ),
        migrations.AddField(
            model_name='researchproject',
            name='publications',
            field=models.ManyToManyField(blank=True, related_name='projects', to='research.researchpublication'),
        ),
        migrations.AddField(
            model_name='researchdataset',
            name='related_publications',
            field=models.ManyToManyField(blank=True, related_name='datasets', to='research.researchpublication'),
        ),
        migrations.AddField(
            model_name='literaturereview',
            name='related_publications',
            field=models.ManyToManyField(blank=True, related_name='literature_reviews', to='research.researchpublication'),
        ),
        migrations.AddField(
            model_name='researchtool',
            name='developers',
            field=models.ManyToManyField(blank=True, related_name='developed_tools', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='researchtool',
            name='maintainers',
            field=models.ManyToManyField(blank=True, related_name='maintained_tools', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='researchtool',
            name='related_projects',
            field=models.ManyToManyField(blank=True, related_name='tools', to='research.researchproject'),
        ),
        migrations.AddField(
            model_name='researchtool',
            name='related_publications',
            field=models.ManyToManyField(blank=True, related_name='tools', to='research.researchpublication'),
        ),
        migrations.AddIndex(
            model_name='researchpublication',
            index=models.Index(fields=['slug', 'publication_type'], name='research_re_slug_6bd890_idx'),
        ),
        migrations.AddIndex(
            model_name='researchpublication',
            index=models.Index(fields=['publication_date', 'is_published'], name='research_re_publica_7ca040_idx'),
        ),
        migrations.AddIndex(
            model_name='researchpublication',
            index=models.Index(fields=['doi', 'is_published'], name='research_re_doi_72c65d_idx'),
        ),
        migrations.AddIndex(
            model_name='researchproject',
            index=models.Index(fields=['slug', 'status'], name='research_re_slug_3bb905_idx'),
        ),
        migrations.AddIndex(
            model_name='researchproject',
            index=models.Index(fields=['principal_investigator', 'status'], name='research_re_princip_892f4d_idx'),
        ),
        migrations.AddIndex(
            model_name='researchdataset',
            index=models.Index(fields=['slug', 'dataset_type'], name='research_re_slug_302b58_idx'),
        ),
        migrations.AddIndex(
            model_name='researchdataset',
            index=models.Index(fields=['doi', 'is_verified'], name='research_re_doi_898956_idx'),
        ),
    ]
