# Generated by Django 5.2.7 on 2025-12-24 17:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('partners', '0002_initial'),
        ('programs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='coordinators',
            field=models.ManyToManyField(blank=True, related_name='coordinated_programs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='program',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_programs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='program',
            name='funding_partners',
            field=models.ManyToManyField(blank=True, to='partners.partnerorganization'),
        ),
        migrations.AddField(
            model_name='program',
            name='mentors',
            field=models.ManyToManyField(blank=True, related_name='mentored_programs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='program',
            name='partners',
            field=models.ManyToManyField(blank=True, related_name='partnered_programs', to='partners.partnerorganization'),
        ),
        migrations.AddField(
            model_name='program',
            name='program_lead',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='led_programs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='programapplication',
            name='applicant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='program_applications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='programapplication',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='programs.program'),
        ),
        migrations.AddField(
            model_name='programapplication',
            name='reviewer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_applications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='program',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='programs', to='programs.programcategory'),
        ),
        migrations.AddField(
            model_name='programevent',
            name='presenters',
            field=models.ManyToManyField(blank=True, related_name='presented_events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='programevent',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='programs.program'),
        ),
        migrations.AddField(
            model_name='programparticipant',
            name='application',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='programs.programapplication'),
        ),
        migrations.AddField(
            model_name='programparticipant',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='programs.program'),
        ),
        migrations.AddField(
            model_name='programparticipant',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='program_participations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='programresource',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='programs.program'),
        ),
        migrations.AddField(
            model_name='programresource',
            name='uploaded_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='programevent',
            name='resources',
            field=models.ManyToManyField(blank=True, to='programs.programresource'),
        ),
        migrations.AddField(
            model_name='programupdate',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='programupdate',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='updates', to='programs.program'),
        ),
        migrations.AlterUniqueTogether(
            name='programapplication',
            unique_together={('program', 'applicant')},
        ),
        migrations.AddIndex(
            model_name='program',
            index=models.Index(fields=['slug', 'status'], name='programs_pr_slug_267f47_idx'),
        ),
        migrations.AddIndex(
            model_name='program',
            index=models.Index(fields=['program_type', 'status'], name='programs_pr_program_cfed8f_idx'),
        ),
        migrations.AddIndex(
            model_name='program',
            index=models.Index(fields=['is_featured', 'is_published'], name='programs_pr_is_feat_534a0f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='programparticipant',
            unique_together={('program', 'user')},
        ),
    ]
